QAWizardDesignRes = {
    "AccessCode": "授权码",
    "AssigneeFullName": "AssigneeFullName",
    "Comments": "注释",
    "CurrentlySubmittingDefault": "提交表格",
    "DefaultDownloadPageTitle": "文件",
    "DefaultFinishTitle": "完成",
    "DefaultGeneratingText": "正在创建您的文档",
    "DefaultInvalidProjectText": "[ErrorPage]页面包含无效的答案。在继续之前请纠正。",
    "DefaultOnlineRedirectMessage": "已经提交您的回应",
    "DefaultWorkflowTransitionEmail": "\u003cp\u003e[ProjectLink]\u003c/p\u003e\r\n\u003cP\u003e评论\u003cbr\u003e\r\n[Comments]\u003c/p\u003e",
    "DefaultWorkflowTransitionEmailSubject": "[ProjectName] - [StateName]",
    "FileNameWithoutBlanks": "文件名",
    "FinishState": "（完成）",
    "FirstNameAndLastNameRequired": "添加到联系人时需要姓和名",
    "FormDefaultDownloadPageTitle": "完成",
    "FormDefaultGenerateButtonText": "提交",
    "FormDefaultGeneratingText": "提交表格",
    "FormQueueMessage": "表格已等候排队，并将在连接可用时提交",
    "None": "（没有）",
    "NoNextState": "此项任务没有下一步。",
    "NotContain": "不含",
    "NotEqual": "不等于",
    "NumericType": "须有有效号码",
    "PleaseEnterAComment": "请输入评论。",
    "PleaseSelectNextState": "请为此任务选择下一步。",
    "PleaseSelectNextUser": "请选择将此任务发至人员。",
    "Printer": "打印机",
    "ProjectLink": "ProjectLink",
    "ProjectName": "ProjectName",
    "PublishedProjectNotFound": "未找到已发布的项目",
    "RowCount": "RowCount",
    "RowId": "RowId",
    "RowNumber": "RowNumber",
    "StartState": "（开始）",
    "StateName": "StateName",
    "WorkflowId": "WorkflowId",
    "WorkflowStepCompleteDefault": "表格提交 - 步骤完成"
}