QAWizardDesignRes = {
    "AccessCode": "Access Code",
    "AssigneeFullName": "AssigneeFullName",
    "Comments": "Comments",
    "CurrentlySubmittingDefault": "Submitting Form",
    "DefaultDownloadPageTitle": "Documentos",
    "DefaultFinishTitle": "Terminar",
    "DefaultGeneratingText": "Criando seu(s) Documento(s)",
    "DefaultInvalidProjectText": "[PáginaDeErro] página contém respostas inválidas. Por favor corrija-as antes de continuar",
    "DefaultOnlineRedirectMessage": "Your answers have been submitted",
    "DefaultWorkflowTransitionEmail": "\u003cp\u003e[ProjectLink]\u003c/p\u003e\r\n\u003cp\u003eComments\u003cbr\u003e\r\n[Comments]\u003c/p\u003e",
    "DefaultWorkflowTransitionEmailSubject": "[ProjectName] - [StateName]",
    "FileNameWithoutBlanks": "Filename",
    "FinishState": "(Terminar)",
    "FirstNameAndLastNameRequired": "Primeiro e último nome são exigidos para adicionar a contatos",
    "FormDefaultDownloadPageTitle": "Terminar",
    "FormDefaultGenerateButtonText": "Submeter",
    "FormDefaultGeneratingText": "Submetendo suas Respostas",
    "FormQueueMessage": "Form has been queued and will be submitted when a connection is available",
    "None": "(Nenhum)",
    "NoNextState": "There is no next step for this task.",
    "NotContain": "Não conter",
    "NotEqual": "Não igual",
    "NumericType": "Um número válido é exigido",
    "PleaseEnterAComment": "Please enter a comment.",
    "PleaseSelectNextState": "Please select the next step for this task.",
    "PleaseSelectNextUser": "Please select the person to send this task to.",
    "Printer": "Impressora",
    "ProjectLink": "ProjectLink",
    "ProjectName": "ProjectName",
    "PublishedProjectNotFound": "Published Project(s) not found",
    "RowCount": "RowCount",
    "RowId": "RowId",
    "RowNumber": "RowNumber",
    "StartState": "(Começar)",
    "StateName": "StateName",
    "WorkflowId": "WorkflowId",
    "WorkflowStepCompleteDefault": "Form submitted - step complete"
}