QAWizardDesignRes = {
    "AccessCode": "Access Code",
    "AssigneeFullName": "AssigneeFullName",
    "Comments": "ความคิดเห็น",
    "CurrentlySubmittingDefault": "แบบฟอร์มที่ส่งมา",
    "DefaultDownloadPageTitle": "เอกสาร",
    "DefaultFinishTitle": "เสร็จสิ้น",
    "DefaultGeneratingText": "การสร้างเอกสารของคุณ",
    "DefaultInvalidProjectText": "[หน้าที่ผิดพลาด] หน้านี้มีข้อผิดพลาด กรุณาแก้ไขก่อนที่จะดำเนินการต่อ",
    "DefaultOnlineRedirectMessage": "Your answers have been submitted",
    "DefaultWorkflowTransitionEmail": "\u003cp\u003e[เชื่อมต่อโครงการ]\u003c/p\u003e     \u003cp\u003eคำแนะนำ\u003cbr\u003e         [คำแนะนำ]\u003c/p\u003e",
    "DefaultWorkflowTransitionEmailSubject": "[ชื่อโครงการ]-[คำบรรยายชื่อโครงการ]",
    "FileNameWithoutBlanks": "Filename",
    "FinishState": "(เสร็จสิ้น)",
    "FirstNameAndLastNameRequired": "เมื่อมีการเพิ่มเติมรายชื่อจำเป็นต้องมีชื่อและนามสกุล",
    "FormDefaultDownloadPageTitle": "เสร็จสิ้น",
    "FormDefaultGenerateButtonText": "ส่ง",
    "FormDefaultGeneratingText": "แบบฟอร์มที่ส่งมา",
    "FormQueueMessage": "Form has been queued and will be submitted when a connection is available",
    "None": "(ไม่มี)",
    "NoNextState": "ไม่มีขั้นตอนต่อไปสำหรับงานนี้",
    "NotContain": "ไม่มี",
    "NotEqual": "ไม่เท่ากัน",
    "NumericType": "จำเป็นต้องมีหมายเลขที่ถูกต้อง",
    "PleaseEnterAComment": "กรุณาใส่ความคิดเห็น",
    "PleaseSelectNextState": "กรุณาเลือกขั้นตอนต่อไปสำหรับงานนี้",
    "PleaseSelectNextUser": "กรุณาเลือกผู้รับสำหรับการส่งงานนี้",
    "Printer": "เครื่องพิมพ์",
    "ProjectLink": "โครงการเชื่อมโยง",
    "ProjectName": "ชื่อโครงการ",
    "PublishedProjectNotFound": "ไม่พบโครงการที่ถูกตีพิมพ์",
    "RowCount": "RowCount",
    "RowId": "RowId",
    "RowNumber": "RowNumber",
    "StartState": "(เริ่มต้น)",
    "StateName": "คำบรรยายชื่อโครงการ",
    "WorkflowId": "WorkflowId",
    "WorkflowStepCompleteDefault": "แบบฟอร์มได้ส่งไปแล้ว - เสร็จสิ้นขั้นตอน"
}