QAWizardDesignRes = {
    "AccessCode": "Access Code",
    "AssigneeFullName": "NombreCompletoPersonaAsignada",
    "Comments": "Comentarios",
    "CurrentlySubmittingDefault": "Formulario Enviado",
    "DefaultDownloadPageTitle": "Documentos",
    "DefaultFinishTitle": "Finalizar",
    "DefaultGeneratingText": "Creando su documento (s)",
    "DefaultInvalidProjectText": "[ErrorPage] contiene respuestas no válidas. Utilice el menú de progreso de la izquierda para corregirlos antes de continuar.",
    "DefaultOnlineRedirectMessage": "Your answers have been submitted",
    "DefaultWorkflowTransitionEmail": "\u003cp\u003e[ProjectLink]\u003c/p\u003e\n\u003cp\u003eComentarios\u003cbr\u003e\n[Comentarios]\u003c/p\u003e",
    "DefaultWorkflowTransitionEmailSubject": "[NombreProyecto] - [NombreEstado]",
    "FileNameWithoutBlanks": "NombreArchivo",
    "FinishState": "(Finalizar)",
    "FirstNameAndLastNameRequired": "Es necesario incluir el nombre y los apellidos al añadir contactos",
    "FormDefaultDownloadPageTitle": "Finalizar",
    "FormDefaultGenerateButtonText": "Enviar",
    "FormDefaultGeneratingText": "Enviar sus respuestas",
    "FormQueueMessage": "Form has been queued and will be submitted when a connection is available",
    "None": "(Ninguno)",
    "NoNextState": "No existe siguiente paso para esta tarea",
    "NotContain": "No contiene",
    "NotEqual": "No es igual a",
    "NumericType": "Un número válido es requerido",
    "PleaseEnterAComment": "Por favor ingrese un comentario",
    "PleaseSelectNextState": "Por favor seleccione el siguiente paso para esta tarea",
    "PleaseSelectNextUser": "Por favor seleccione la persona para enviar esta tarea",
    "Printer": "Impresora",
    "ProjectLink": "ProjectLink",
    "ProjectName": "NombeProyecto",
    "PublishedProjectNotFound": "Proyecto(s) publicados no encontrados",
    "RowCount": "RowCount",
    "RowId": "IdFila",
    "RowNumber": "RowNumber",
    "StartState": "(Iniciar)",
    "StateName": "Nombre de estado",
    "WorkflowId": "WorkflowId",
    "WorkflowStepCompleteDefault": "Formulario enviado - paso completado"
}