QAWizardDesignRes = {
    "AccessCode": "Access Code",
    "AssigneeFullName": "AssigneeFullName",
    "Comments": "Comments",
    "CurrentlySubmittingDefault": "Submitting Form",
    "DefaultDownloadPageTitle": "Documents",
    "DefaultFinishTitle": "Finish",
    "DefaultGeneratingText": "Creating your Documents",
    "DefaultInvalidProjectText": "[ErrorPage] page contains invalid answers. Please correct them before continuing.",
    "DefaultOnlineRedirectMessage": "Your answers have been submitted",
    "DefaultWorkflowTransitionEmail": "\u003cp\u003e[ProjectLink]\u003c/p\u003e\r\n\u003cp\u003eComments\u003cbr\u003e\r\n[Comments]\u003c/p\u003e",
    "DefaultWorkflowTransitionEmailSubject": "[ProjectName] - [StateName]",
    "FileNameWithoutBlanks": "Filename",
    "FinishState": "(Finish)",
    "FirstNameAndLastNameRequired": "First and last names are required when adding to contacts",
    "FormDefaultDownloadPageTitle": "Finish",
    "FormDefaultGenerateButtonText": "Submit",
    "FormDefaultGeneratingText": "Submitting Form",
    "FormQueueMessage": "Form has been queued and will be submitted when a connection is available",
    "None": "(None)",
    "NoNextState": "There is no next step for this task.",
    "NotContain": "not contain",
    "NotEqual": "not equal",
    "NumericType": "A valid number is required",
    "PleaseEnterAComment": "Please enter a comment.",
    "PleaseSelectNextState": "Please select the next step for this task.",
    "PleaseSelectNextUser": "Please select the person to send this task to.",
    "Printer": "Printer",
    "ProjectLink": "ProjectLink",
    "ProjectName": "ProjectName",
    "PublishedProjectNotFound": "Published Project(s) not found",
    "RowCount": "RowCount",
    "RowId": "RowId",
    "RowNumber": "RowNumber",
    "StartState": "(Start)",
    "StateName": "StateName",
    "WorkflowId": "WorkflowId",
    "WorkflowStepCompleteDefault": "Form submitted - step complete"
}