QAWizardDesignRes = {
    "AccessCode": "Access Code",
    "AssigneeFullName": "Vollständiger Name der zugewiesenen Person",
    "Comments": "Kommentare",
    "CurrentlySubmittingDefault": "Formular übertragen",
    "DefaultDownloadPageTitle": "Dokumente",
    "DefaultFinishTitle": "beenden/abschliessen",
    "DefaultGeneratingText": "Ihr ( e) Dokument( e) werden erstellt",
    "DefaultInvalidProjectText": "[Fehlerseite] Seite enthält ungültige Antworten. Bitte korrigieren Sie diese, um fortzusetzen.",
    "DefaultOnlineRedirectMessage": "Your answers have been submitted",
    "DefaultWorkflowTransitionEmail": "\u003cp\u003e[ProjektLink]\u003c/p\u003e\r\n\u003cp\u003eKommentare\u003cbr\u003e\r\n[Kommentare]\u003c/p\u003e",
    "DefaultWorkflowTransitionEmailSubject": "[ProjektName] - [StatusName]",
    "FileNameWithoutBlanks": "Dateiname",
    "FinishState": "(beenden)(abschließen)",
    "FirstNameAndLastNameRequired": "Vor- und Nachnamen sind erforderlich beim Hinzufügen zu den Kontakten",
    "FormDefaultDownloadPageTitle": "Abschliessen",
    "FormDefaultGenerateButtonText": "Senden",
    "FormDefaultGeneratingText": "Formular senden",
    "FormQueueMessage": "Form has been queued and will be submitted when a connection is available",
    "None": "(Kein/e/r)",
    "NoNextState": "Kein nächster Schritt für diese Aufgabe angegeben",
    "NotContain": "Enthält nicht",
    "NotEqual": "Ungleich",
    "NumericType": "Eine gültige Zahl ist erforderlich",
    "PleaseEnterAComment": "Bitte geben Sie hier einen Kommentar ein",
    "PleaseSelectNextState": "Bitte wählen Sie den nächsten Schritt für diese Aufgabe aus.",
    "PleaseSelectNextUser": "Bitte wählen Sie die Person aus, an welche Sie diese Aufgabe senden wollen",
    "Printer": "Drucker",
    "ProjectLink": "ProjektLink",
    "ProjectName": "Projektname",
    "PublishedProjectNotFound": "Veröffentlichte Projekt ( e) nicht gefunden",
    "RowCount": "Zeilenzahl",
    "RowId": "RowId",
    "RowNumber": "Zeilennummer",
    "StartState": "(Start)",
    "StateName": "StatusName",
    "WorkflowId": "WorkflowId",
    "WorkflowStepCompleteDefault": "Formular gesendet - Schritt abgeschlossen"
}