QAWizardDesignRes = {
    "AccessCode": "Ontvanger naam",
    "AssigneeFullName": "Achtergrulld kleur bij AssigneeFullName",
    "Comments": "commentaar",
    "CurrentlySubmittingDefault": "Ontvanger naam",
    "DefaultDownloadPageTitle": "Documenten",
    "DefaultFinishTitle": "Voltooien",
    "DefaultGeneratingText": "Uw document(en) aanmaken",
    "DefaultInvalidProjectText": "[Foutpagina] pagina bevat ongeldige antwoorden. Corrigeer ze voordat je verdergaat.",
    "DefaultOnlineRedirectMessage": "Uw antwoorden zijn ingedient",
    "DefaultWorkflowTransitionEmail": "\u003cP\u003e [ProjectLINK] \u003c/ p\u003e \u003cP\u003e Reacties \u003cbr\u003e [Reacties] \u003c/ p\u003e",
    "DefaultWorkflowTransitionEmailSubject": "[ProjectNaam] - [ToestandNaam]",
    "FileNameWithoutBlanks": "Filenaam",
    "FinishState": "(klaar)",
    "FirstNameAndLastNameRequired": "Voor en achternaam zijn noodzakelijk voor het toevoegen van contacten",
    "FormDefaultDownloadPageTitle": "Voltooien",
    "FormDefaultGenerateButtonText": "Invoeren",
    "FormDefaultGeneratingText": "Uw antwoorden invoeren",
    "FormQueueMessage": "Achtergrisd kleur bij available",
    "None": "(Geen)",
    "NoNextState": "Achtergrthisd kleur bij task.",
    "NotContain": "bevat niet",
    "NotEqual": "niet gelijk aan",
    "NumericType": "Geldig aantal vereist",
    "PleaseEnterAComment": "Achtergrad kleur bij comment.",
    "PleaseSelectNextState": "Selecteer de volgende stap voor deze taak",
    "PleaseSelectNextUser": "Selecteer de persoon voor deze taak",
    "Printer": "Printer",
    "ProjectLink": "Ontvanger naam",
    "ProjectName": "Ontvanger naam",
    "PublishedProjectNotFound": "Ontvanger naam",
    "RowCount": "Ontvanger naam",
    "RowId": "Ontvanger naam",
    "RowNumber": "Ontvanger naam",
    "StartState": "(Start)",
    "StateName": "Ontvanger naam",
    "WorkflowId": "Ontvanger naam",
    "WorkflowStepCompleteDefault": "Formulier verzonden - stap compleet"
}